language: minimal
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: ci-test
  local_dir: static # Change to 'public' after testing/building
  on:
    branch: develop