language: minimal  # We don't need any language support
dist: bionic  # Currently the latest Ubuntu LTS
addons:
  snaps:
    - name: zola  # We only need to install zola...
      channel: latest/edge
script:
  - zola build  # ... build the website ...
deploy:  # ... and then 'deploy' it by pushing it to `master`!
  provider: pages  # See https://docs.travis-ci.com/user/deployment/pages/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # This environment variable was set in Travis' repository settings
  keep_history: true
  target_branch: master  # Push the site to the `master` branch
  local_dir: public  # Push the contents of this directory. (Zola makes it and puts the site in it)
  fqdn: www.hankruiger.com  # This makes sure that a CNAME is added
  on:
    branch: develop  # Only spawn a job when pushed to `develop`

# GitHub pages takes care of the rest