language: minimal
dist: bionic
addons:
  snaps:
    - name: zola
      channel: latest/edge
script:
  - zola build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  local_dir: public
  on:
    branch: develop