language: minimal
dist: bionic
addons:
  snaps:
    - name: zola
      channel: latest/edge
before-deploy:
  - zola --version
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: ci-test
  local_dir: static
  on:
    branch: develop